# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templates/designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1321, 794)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("templates\\../imagens/icone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(145, 145, 145, 255), stop:0.762712 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_circ_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.label_circ_1.sizePolicy().hasHeightForWidth())
        self.label_circ_1.setSizePolicy(sizePolicy)
        self.label_circ_1.setMinimumSize(QtCore.QSize(25, 25))
        self.label_circ_1.setMaximumSize(QtCore.QSize(25, 25))
        self.label_circ_1.setBaseSize(QtCore.QSize(25, 25))
        self.label_circ_1.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.420455 rgba(143, 143, 143, 255), stop:1 rgba(93, 93, 93, 255));\n"
"border-radius: 12%;")
        self.label_circ_1.setText("")
        self.label_circ_1.setObjectName("label_circ_1")
        self.gridLayout_2.addWidget(self.label_circ_1, 0, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(600, 400))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setBaseSize(QtCore.QSize(1024, 768))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelImagem = QtWidgets.QLabel(self.frame)
        self.labelImagem.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImagem.sizePolicy().hasHeightForWidth())
        self.labelImagem.setSizePolicy(sizePolicy)
        self.labelImagem.setMinimumSize(QtCore.QSize(800, 600))
        self.labelImagem.setFrameShape(QtWidgets.QFrame.Box)
        self.labelImagem.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelImagem.setText("")
        self.labelImagem.setPixmap(QtGui.QPixmap("templates\\../imagens/Logo Stone Photo Studio SP.png"))
        self.labelImagem.setScaledContents(True)
        self.labelImagem.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImagem.setObjectName("labelImagem")
        self.gridLayout_4.addWidget(self.labelImagem, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 11, 16, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(251, 251, 251);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 11, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(251, 251, 251);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 15, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(251, 251, 251);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 12, 0, 1, 1)
        self.btnCapturar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCapturar.sizePolicy().hasHeightForWidth())
        self.btnCapturar.setSizePolicy(sizePolicy)
        self.btnCapturar.setMinimumSize(QtCore.QSize(0, 0))
        self.btnCapturar.setMaximumSize(QtCore.QSize(410, 16777215))
        self.btnCapturar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCapturar.setStyleSheet(":hover {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(229, 241, 251, 255), stop:0.762712 rgba(255, 255, 255, 255))}")
        self.btnCapturar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("templates\\../imagens/cameraOFF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCapturar.setIcon(icon1)
        self.btnCapturar.setIconSize(QtCore.QSize(240, 240))
        self.btnCapturar.setObjectName("btnCapturar")
        self.gridLayout_2.addWidget(self.btnCapturar, 1, 0, 1, 6)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        self.label_11.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(251, 251, 251);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 13, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(251, 251, 251);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 10, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
"border: none;\n"
"border-radius: 5%;\n"
"padding: 5px;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1px solid #838383;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"border: none;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1.5px solid #003ae5;\n"
"}\n"
"QLineEdit:focus:hover {\n"
"border: none;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1px solid #838383;\n"
"\n"
"}")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 14, 2, 1, 4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setMaxLength(2)
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 10, 5, 1, 1)
        self.comboBox_espessura = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_espessura.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_espessura.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_espessura.setFont(font)
        self.comboBox_espessura.setStyleSheet("QComboBox {\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.comboBox_espessura.setEditable(False)
        self.comboBox_espessura.setCurrentText("")
        self.comboBox_espessura.setMaxVisibleItems(10)
        self.comboBox_espessura.setFrame(True)
        self.comboBox_espessura.setObjectName("comboBox_espessura")
        self.gridLayout_2.addWidget(self.comboBox_espessura, 10, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"border: none;\n"
"border-radius: 5%;\n"
"padding: 5px;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1px solid #838383;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"border: none;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1.5px solid #003ae5;\n"
"}\n"
"QLineEdit:focus:hover {\n"
"border: none;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1px solid #838383;\n"
"\n"
"}")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 13, 2, 1, 4)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("QLineEdit {\n"
"border: none;\n"
"border-radius: 5%;\n"
"padding: 5px;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1px solid #838383;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"border: none;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1.5px solid #003ae5;\n"
"}\n"
"QLineEdit:focus:hover {\n"
"border: none;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1px solid #838383;\n"
"\n"
"}")
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 15, 2, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(251, 251, 251);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 14, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(255, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"border: none;\n"
"border-radius: 5%;\n"
"padding: 5px;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1px solid #838383;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"border: none;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1.5px solid #003ae5;\n"
"}\n"
"QLineEdit:focus:hover {\n"
"border: none;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1px solid #838383;\n"
"\n"
"}")
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 12, 2, 1, 4)
        self.lineEdit_codigoDeBarras = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_codigoDeBarras.sizePolicy().hasHeightForWidth())
        self.lineEdit_codigoDeBarras.setSizePolicy(sizePolicy)
        self.lineEdit_codigoDeBarras.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_codigoDeBarras.setMaximumSize(QtCore.QSize(255, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_codigoDeBarras.setFont(font)
        self.lineEdit_codigoDeBarras.setStyleSheet("QLineEdit {\n"
"border: none;\n"
"border-radius: 5%;\n"
"padding: 5px;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1px solid #838383;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"border: none;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1.5px solid #003ae5;\n"
"}\n"
"QLineEdit:focus:hover {\n"
"border: none;\n"
"border: 0.5px solid rgba(131, 131, 131, 50);\n"
"border-bottom: 1px solid #838383;\n"
"\n"
"}")
        self.lineEdit_codigoDeBarras.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_codigoDeBarras.setClearButtonEnabled(False)
        self.lineEdit_codigoDeBarras.setObjectName("lineEdit_codigoDeBarras")
        self.gridLayout_2.addWidget(self.lineEdit_codigoDeBarras, 11, 2, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(251, 251, 251);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 10, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(251, 251, 251);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 8, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 10, 3, 1, 1)
        self.comboBox_material = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_material.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_material.setFont(font)
        self.comboBox_material.setAutoFillBackground(False)
        self.comboBox_material.setStyleSheet("QComboBox {\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.comboBox_material.setEditable(False)
        self.comboBox_material.setCurrentText("")
        self.comboBox_material.setFrame(True)
        self.comboBox_material.setObjectName("comboBox_material")
        self.gridLayout_2.addWidget(self.comboBox_material, 8, 2, 1, 4)
        self.btnCrop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCrop.sizePolicy().hasHeightForWidth())
        self.btnCrop.setSizePolicy(sizePolicy)
        self.btnCrop.setMinimumSize(QtCore.QSize(0, 80))
        self.btnCrop.setMaximumSize(QtCore.QSize(410, 16777215))
        self.btnCrop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCrop.setStyleSheet(":hover {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(229, 241, 251, 255), stop:0.762712 rgba(255, 255, 255, 255))}")
        self.btnCrop.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("templates\\../imagens/crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCrop.setIcon(icon2)
        self.btnCrop.setIconSize(QtCore.QSize(54, 54))
        self.btnCrop.setObjectName("btnCrop")
        self.gridLayout_2.addWidget(self.btnCrop, 7, 2, 1, 2)
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnVoltar.sizePolicy().hasHeightForWidth())
        self.btnVoltar.setSizePolicy(sizePolicy)
        self.btnVoltar.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnVoltar.setFont(font)
        self.btnVoltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVoltar.setStyleSheet(":hover {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(229, 241, 251, 255), stop:0.762712 rgba(255, 255, 255, 255))}")
        self.btnVoltar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("templates\\../imagens/voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVoltar.setIcon(icon3)
        self.btnVoltar.setIconSize(QtCore.QSize(54, 54))
        self.btnVoltar.setObjectName("btnVoltar")
        self.gridLayout_2.addWidget(self.btnVoltar, 7, 4, 1, 2)
        self.btnSalvar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSalvar.sizePolicy().hasHeightForWidth())
        self.btnSalvar.setSizePolicy(sizePolicy)
        self.btnSalvar.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSalvar.setFont(font)
        self.btnSalvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSalvar.setStyleSheet(":hover {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(229, 241, 251, 255), stop:0.762712 rgba(255, 255, 255, 255))}")
        self.btnSalvar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("templates\\../imagens/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon4)
        self.btnSalvar.setIconSize(QtCore.QSize(60, 60))
        self.btnSalvar.setObjectName("btnSalvar")
        self.gridLayout_2.addWidget(self.btnSalvar, 7, 0, 1, 2)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setMinimumSize(QtCore.QSize(0, 0))
        self.label_status.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.gridLayout_2.addWidget(self.label_status, 2, 0, 3, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1321, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("background-color: rgb(146, 146, 146);")
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(252, 252, 252);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConfigurar_Servidor = QtWidgets.QAction(MainWindow)
        self.actionConfigurar_Servidor.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionConfigurar_Servidor.setObjectName("actionConfigurar_Servidor")
        self.actionFechar = QtWidgets.QAction(MainWindow)
        self.actionFechar.setObjectName("actionFechar")
        self.actionConfigurar_Material = QtWidgets.QAction(MainWindow)
        self.actionConfigurar_Material.setObjectName("actionConfigurar_Material")
        self.menuMenu.addAction(self.actionConfigurar_Servidor)
        self.menuMenu.addAction(self.actionConfigurar_Material)
        self.menuMenu.addAction(self.actionFechar)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_codigoDeBarras, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.lineEdit_8)
        MainWindow.setTabOrder(self.lineEdit_8, self.lineEdit_9)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stone Photo Studio"))
        self.label_5.setText(_translate("MainWindow", "Código de Barras:"))
        self.label_10.setText(_translate("MainWindow", "Sequência Executada:"))
        self.label_7.setText(_translate("MainWindow", "N° Bloco Sistema:"))
        self.label_11.setText(_translate("MainWindow", "Conexão com Servidor"))
        self.label_8.setText(_translate("MainWindow", "Sequência Resumida:"))
        self.label_3.setText(_translate("MainWindow", "Espessura:"))
        self.lineEdit_5.setText(_translate("MainWindow", "5"))
        self.label_9.setText(_translate("MainWindow", "Sequência para Execução:"))
        self.label_6.setText(_translate("MainWindow", "Timer:"))
        self.label.setText(_translate("MainWindow", "Nome do Material:"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "N° Bundle"))
        self.label_status.setText(_translate("MainWindow", "Status"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionConfigurar_Servidor.setText(_translate("MainWindow", "Configurar Servidor"))
        self.actionFechar.setText(_translate("MainWindow", "Fechar"))
        self.actionConfigurar_Material.setText(_translate("MainWindow", "Configurar Material"))
